services:
  - type: web
    name: rag-qa-app
    env: docker
    dockerfilePath: ./Dockerfile.vercel
    plan: free
    envVars:
      - key: PORT
        value: 8000
      - key: ENVIRONMENT
        value: production
    healthCheckPath: /health
